function postToGoogle() {

  // capture input values, store in variables
  var fullname = document.forms[0].elements.fullname.value;
  var email = document.forms[0].elements.email.value;
  var message = document.forms[0].elements.message.value;

  // The following is Ajax -- what allows two-way communication
  // with our page and Google's servers. jQuery is used here to
  // make the code a little easier.

  $.ajax({
    // url: the url generated for the form's action attribute
    // remember to replace uniqueId
    url: "https://docs.google.com/forms/d/1o0F7Cinya9_HcxrhdDnYjmFe3Urh8DYW5dlQVjCp4lo/formResponse",
    data: {
      // each entry corresponds with a form field as generated by
      // Google's Form Builder; remember to replace uniqueId
      "entry.636323937": fullname,
      "entry.1229096238": email,
      "entry.625436445": message
    },
    // we POST the data, sending it in the 'json' format
    type: "POST",
    dataType: "json",
    // we execute an action when the status code is 200 (OK)
    // in this case, we re-direct the user to a page thanking
    // them for their submission. The 0 status code is a
    // default, catch-all
    statusCode: {
      0: function() {
        window.location.replace("thank-you.html");
      },
      200: function() {
        window.location.replace("thank-you.html");
      }
    }
  });
}

// identify the submit button
var send= document.forms[0].elements.send;

// add an event listener to submit
send.addEventListener("click", function() {
  // prevent the page from refreshing
  event.preventDefault();
  // call the postToGoogle() function
  postToGoogle();
}, false);
